[ABOUT]
NAME=GT7 Replay UI
AUTHOR=lem, lint0
VERSION = 0.1
REQUIRED_VERSION = 3748 ; 0.3.0-preview211
DESCRIPTION=GT7 Replay UI replica for Assetto Corsa

[CORE]
LAZY = 1

[WINDOW_...]
ID = main
NAME = GT7 Replay
; ICON = ./ico/icon.png
FUNCTION_MAIN = windowMain
FUNCTION_SETTINGS = windowSettings
; FUNCTION_ON_SHOW = init
FLAGS = NO_TITLE_BAR, NO_COLLAPSE, NO_BACKGROUND, NO_SCROLLBAR, FULLSCREEN